# ============================================
# AI Research Agent - Research State Schema
# ============================================
"""
State design for the LangGraph research workflow.

THIS IS THE MOST IMPORTANT FILE IN THE PROJECT.
================================================

In LangGraph, STATE is everything. The state:
- Defines what data flows between nodes
- Controls what each node can read and write
- Determines how the graph remembers progress
- Enables checkpointing and resumption

HOW LANGGRAPH STATE WORKS:
--------------------------
1. You define a TypedDict or Pydantic model as your state schema.
2. Each node receives the FULL state as input.
3. Each node returns a PARTIAL state update (delta).
4. LangGraph MERGES the delta into the existing state.
5. The next node receives the updated state.

Example flow:
    State: {user_query: "quantum computing", search_results: []}
         ↓ Planner Node returns: {search_queries: ["quantum computing 2025"]}
    State: {user_query: "quantum computing", search_results: [], search_queries: ["quantum computing 2025"]}
         ↓ Searcher Node returns: {search_results: [Result1, Result2]}
    State: {user_query: "quantum computing", search_results: [Result1, Result2], search_queries: [...]}

REDUCERS (Annotated types):
---------------------------
For list fields that should ACCUMULATE (not replace), we use reducers.
    Annotated[list[str], operator.add]
This means: when a node returns {"errors": ["new error"]}, it APPENDS
to the existing list instead of replacing it.

Without reducers:
    Node 1 returns: {errors: ["error1"]}  → state.errors = ["error1"]
    Node 2 returns: {errors: ["error2"]}  → state.errors = ["error2"]  ← ERROR1 LOST!

With reducers:
    Node 1 returns: {errors: ["error1"]}  → state.errors = ["error1"]
    Node 2 returns: {errors: ["error2"]}  → state.errors = ["error1", "error2"]  ← BOTH KEPT!

DESIGN DECISIONS:
-----------------
- We use Pydantic models for NESTED data (SearchResult, SourceSummary)
  because they need validation and clear schemas.
- We use TypedDict for the TOP-LEVEL state because LangGraph requires it
  for reducer annotations.
- Every field has a default value so the graph can start with minimal input.
"""

from __future__ import annotations

import operator
from typing import Annotated, Optional
from pydantic import BaseModel, Field


# ============================================
# Pydantic Models for Nested State Data
# ============================================
# These are NOT the graph state itself — they are structured data types
# used INSIDE the state. Think of them as the "vocabulary" of our state.

class SubQuestion(BaseModel):
    """
    A single sub-question from the research plan decomposition.
    
    When a user asks "Compare LangGraph and CrewAI", the planner breaks
    this into smaller, searchable questions like:
    - "What is LangGraph and how does it work?"
    - "What is CrewAI and how does it work?"
    - "LangGraph vs CrewAI performance comparison"
    """
    question: str = Field(description="The sub-question to research")
    priority: int = Field(
        default=1,
        ge=1, le=5,
        description="Priority 1 (highest) to 5 (lowest)"
    )
    search_query: str = Field(
        description="Optimized search query for this sub-question"
    )


class ResearchPlan(BaseModel):
    """
    The structured research plan generated by the Planner node.
    
    This is the "strategy document" that guides the entire research process.
    A good research plan means targeted searches and relevant results.
    A bad plan means wasted API calls and irrelevant information.
    """
    objective: str = Field(
        description="Clear statement of the research objective"
    )
    approach: str = Field(
        description="High-level approach to the research (e.g., 'comparative analysis', 'deep dive', 'survey')"
    )
    sub_questions: list[SubQuestion] = Field(
        default_factory=list,
        description="Decomposed sub-questions to investigate"
    )
    expected_sections: list[str] = Field(
        default_factory=list,
        description="Expected sections in the final report"
    )


class SearchResult(BaseModel):
    """
    A single search result from the web search tool.
    
    Contains the metadata we get back from Tavily: URL, title, snippet.
    The snippet is a short preview — we'll need the Extractor to get
    the full content from the URL.
    """
    url: str = Field(description="URL of the search result")
    title: str = Field(description="Title of the page")
    snippet: str = Field(
        default="",
        description="Short content snippet from the search engine"
    )
    relevance_score: float = Field(
        default=0.0,
        ge=0.0, le=1.0,
        description="Relevance score from the search engine (0.0 to 1.0)"
    )
    query: str = Field(
        default="",
        description="The search query that produced this result"
    )


class ExtractedContent(BaseModel):
    """
    Full content extracted from a web page.
    
    After the Searcher finds URLs, the Extractor visits each URL
    and pulls out the main article text using Trafilatura/BS4.
    This is the RAW material that the Analyzer will summarize.
    """
    url: str = Field(description="Source URL")
    title: str = Field(description="Page title")
    content: str = Field(description="Extracted main content text")
    word_count: int = Field(default=0, description="Word count of extracted content")
    extraction_success: bool = Field(
        default=True,
        description="Whether content extraction was successful"
    )


class SourceSummary(BaseModel):
    """
    A summary of a single source, created by the Analyzer node.
    
    Each source gets its own summary with key findings.
    This is an intermediate step before cross-source comparison.
    """
    url: str = Field(description="Source URL")
    title: str = Field(description="Source title")
    summary: str = Field(description="Condensed summary of the source")
    key_findings: list[str] = Field(
        default_factory=list,
        description="Bullet-point key findings from this source"
    )
    credibility_note: str = Field(
        default="",
        description="Note about source credibility or bias"
    )


class AnalysisResult(BaseModel):
    """
    Cross-source analysis comparing information across all sources.
    
    This is where the real "intelligence" happens — the agent doesn't
    just summarize, it COMPARES. It finds:
    - What do sources agree on? (consensus)
    - Where do they disagree? (contradictions)
    - What unique insights does each source provide? (unique findings)
    """
    agreements: list[str] = Field(
        default_factory=list,
        description="Points where multiple sources agree"
    )
    contradictions: list[str] = Field(
        default_factory=list,
        description="Points where sources contradict each other"
    )
    unique_findings: list[str] = Field(
        default_factory=list,
        description="Unique insights from individual sources"
    )
    confidence_assessment: str = Field(
        default="",
        description="Overall confidence in the findings"
    )
    needs_more_research: bool = Field(
        default=False,
        description="Whether the Analyzer thinks more research is needed"
    )
    additional_queries: list[str] = Field(
        default_factory=list,
        description="New search queries if more research is needed"
    )


class CombinedAnalysis(BaseModel):
    """Batch analysis containing both per-source summaries and cross-source comparison."""
    source_summaries: list[SourceSummary] = Field(
        default_factory=list,
        description="Summaries for each provided source"
    )
    analysis: AnalysisResult = Field(
        default_factory=AnalysisResult,
        description="Cross-source analysis comparing agreements, contradictions, and insights"
    )


class Citation(BaseModel):
    """
    A formatted citation for the final report.
    
    Every claim in the report should be backed by a citation.
    This enables fact-checking and gives the user confidence
    in the research quality.
    """
    id: int = Field(description="Citation number (e.g., [1], [2])")
    url: str = Field(description="Source URL")
    title: str = Field(description="Source title")
    accessed_date: str = Field(
        default="",
        description="Date the source was accessed"
    )


# ============================================
# Top-Level Graph State (TypedDict)
# ============================================
# This is the ACTUAL state schema that LangGraph uses.
# We use TypedDict (not Pydantic) here because LangGraph
# needs Annotated types for reducers, which works better
# with TypedDict.

from typing import TypedDict


class ResearchState(TypedDict, total=False):
    """
    The complete state of a research workflow execution.
    
    total=False means all fields are optional. This is important because:
    - The graph starts with ONLY user_query
    - Each node adds new fields as it progresses
    - We never need to initialize the full state upfront
    
    STATE EVOLUTION THROUGH THE GRAPH:
    
    ┌─────────────┐  user_query = "quantum computing"
    │   START      │  (everything else is empty)
    └──────┬──────┘
           ▼
    ┌─────────────┐  + research_plan = ResearchPlan(...)
    │  PLANNER     │  + search_queries = ["quantum computing 2025", ...]
    └──────┬──────┘
           ▼
    ┌─────────────┐  + search_results = [SearchResult(...), ...]
    │  SEARCHER    │  + execution_log += ["Searched 3 queries, found 12 results"]
    └──────┬──────┘
           ▼
    ┌─────────────┐  + extracted_content = [ExtractedContent(...), ...]
    │  EXTRACTOR   │  + execution_log += ["Extracted content from 5 pages"]
    └──────┬──────┘
           ▼
    ┌─────────────┐  + source_summaries = [SourceSummary(...), ...]
    │  ANALYZER    │  + analysis = AnalysisResult(...)
    └──────┬──────┘  + execution_log += ["Analyzed 5 sources, found 3 agreements"]
           ▼
    ┌─────────────┐  + citations = [Citation(...), ...]
    │  REPORTER    │  + final_report = "# Research Report\n..."
    └──────┬──────┘  + status = "completed"
           ▼
    ┌─────────────┐
    │    END       │  Full state available for response
    └─────────────┘
    """
    
    # ---- Input ----
    user_query: str  # The original research question from the user
    
    # ---- Planning ----
    research_plan: Optional[ResearchPlan]  # Structured research plan
    search_queries: list[str]  # Decomposed search queries
    
    # ---- Search & Extraction ----
    search_results: Annotated[list[SearchResult], operator.add]  # REDUCER: appends
    extracted_content: Annotated[list[ExtractedContent], operator.add]  # REDUCER: appends
    
    # ---- Analysis ----
    source_summaries: list[SourceSummary]  # Per-source summaries
    analysis: Optional[AnalysisResult]  # Cross-source comparison
    
    # ---- Output ----
    citations: list[Citation]  # Formatted citations
    final_report: str  # The complete research report (Markdown)
    
    # ---- Metadata ----
    status: str  # Current status: "planning", "searching", "analyzing", etc.
    current_iteration: int  # Track research iterations (for loop-back limit)
    errors: Annotated[list[str], operator.add]  # REDUCER: error log (appends)
    execution_log: Annotated[list[str], operator.add]  # REDUCER: step trace (appends)
