# ============================================
# AI Research Agent - Searcher Node
# ============================================
"""
The Searcher node executes web searches for each query from the plan.

WHAT IT DOES:
Takes the search_queries from the Planner and runs each one through
the Tavily search API. Collects all results into search_results.

PERFORMANCE OPTIMIZATION:
- Caps maximum queries to 3 top unique queries.
- De-duplicates URLs across queries.
"""

import logging
from backend.state.research_state import ResearchState
from backend.tools.web_search import search_web
from backend.config.settings import get_settings

logger = logging.getLogger(__name__)


def searcher_node(state: ResearchState) -> dict:
    """
    Web Search Execution Node.
    
    Input from state: search_queries
    Output to state: search_results, status, execution_log
    
    Iterates through search queries and collects results.
    Uses the `operator.add` reducer — results accumulate across iterations.
    """
    search_queries = state.get("search_queries", [])
    settings = get_settings()
    
    if not search_queries:
        logger.warning("🔍 Searcher: No search queries to execute")
        return {
            "status": "searched",
            "execution_log": ["Searcher: No search queries available"],
            "errors": ["No search queries were generated by the planner"],
        }
    
    # De-duplicate and cap to top 3 search queries
    search_queries = list(dict.fromkeys(search_queries))[:3]
    
    logger.info(f"🔍 Searcher: Executing {len(search_queries)} search queries")
    
    all_results = []
    for query in search_queries:
        results = search_web(query, max_results=settings.max_search_results)
        all_results.extend(results)
        logger.info(f"🔍 Searcher: '{query}' → {len(results)} results")
    
    # De-duplicate results by URL (different queries might return the same page)
    seen_urls = set()
    unique_results = []
    for result in all_results:
        if result.url not in seen_urls:
            seen_urls.add(result.url)
            unique_results.append(result)
    
    logger.info(
        f"🔍 Searcher: Found {len(all_results)} total results, "
        f"{len(unique_results)} unique after de-duplication"
    )
    
    return {
        "search_results": unique_results,  # APPENDS via reducer
        "status": "searched",
        "execution_log": [
            f"Searched {len(search_queries)} queries, found "
            f"{len(unique_results)} unique results"
        ],
    }
